nohup: ignoring input
2025-07-30 10:25:45,077 INFO     Starting server at tcp:port=8000:interface=0.0.0.0
2025-07-30 10:25:45,078 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2025-07-30 10:25:45,078 INFO     Configuring endpoint tcp:port=8000:interface=0.0.0.0
2025-07-30 10:25:45,078 INFO     Listening on TCP address 0.0.0.0:8000
2025-07-30 10:26:04,775 ERROR    Invalid HTTP_HOST header: 'e57368b43e9a.ngrok-free.app'. You may need to add 'e57368b43e9a.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'e57368b43e9a.ngrok-free.app'. You may need to add 'e57368b43e9a.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:26:17,593 ERROR    Invalid HTTP_HOST header: 'e57368b43e9a.ngrok-free.app'. You may need to add 'e57368b43e9a.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'e57368b43e9a.ngrok-free.app'. You may need to add 'e57368b43e9a.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:26:18,347 ERROR    Invalid HTTP_HOST header: 'e57368b43e9a.ngrok-free.app'. You may need to add 'e57368b43e9a.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'e57368b43e9a.ngrok-free.app'. You may need to add 'e57368b43e9a.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:26:18,520 ERROR    Invalid HTTP_HOST header: 'e57368b43e9a.ngrok-free.app'. You may need to add 'e57368b43e9a.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'e57368b43e9a.ngrok-free.app'. You may need to add 'e57368b43e9a.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:27:54,108 WARNING  Not Found: /static/admin/css/base.css
2025-07-30 10:27:54,108 WARNING  Not Found: /static/admin/css/dark_mode.css
2025-07-30 10:27:54,144 WARNING  Not Found: /static/admin/css/dashboard.css
2025-07-30 10:27:54,145 WARNING  Not Found: /static/admin/css/nav_sidebar.css
2025-07-30 10:27:54,146 WARNING  Not Found: /static/admin/js/theme.js
2025-07-30 10:27:54,146 WARNING  Not Found: /static/admin/css/responsive.css
2025-07-30 10:27:54,209 WARNING  Not Found: /static/admin/js/nav_sidebar.js
2025-07-30 10:27:54,210 WARNING  Not Found: /static/admin/css/dashboard.css
2025-07-30 10:27:54,212 WARNING  Not Found: /static/admin/css/nav_sidebar.css
2025-07-30 10:28:12,648 WARNING  Not Found: /favicon.ico
2025-07-30 10:28:57,968 WARNING  Not Found: /static/admin/css/base.css
2025-07-30 10:28:57,970 WARNING  Not Found: /static/admin/css/dark_mode.css
2025-07-30 10:28:58,033 WARNING  Not Found: /static/admin/css/nav_sidebar.css
2025-07-30 10:28:58,034 WARNING  Not Found: /static/admin/css/dashboard.css
2025-07-30 10:28:58,035 WARNING  Not Found: /static/admin/css/responsive.css
2025-07-30 10:28:58,038 WARNING  Not Found: /static/admin/js/theme.js
2025-07-30 10:28:58,138 WARNING  Not Found: /static/admin/css/nav_sidebar.css
2025-07-30 10:28:58,138 WARNING  Not Found: /static/admin/css/dashboard.css
2025-07-30 10:28:58,139 WARNING  Not Found: /static/admin/js/nav_sidebar.js
2025-07-30 10:28:58,139 WARNING  Not Found: /static/admin/css/responsive.css
2025-07-30 10:28:58,230 WARNING  Not Found: /favicon.ico
2025-07-30 10:29:04,257 WARNING  Not Found: /
2025-07-30 10:29:07,069 WARNING  Not Found: /static/admin/css/base.css
2025-07-30 10:29:07,069 WARNING  Not Found: /static/admin/css/dark_mode.css
2025-07-30 10:29:07,070 WARNING  Not Found: /static/admin/css/nav_sidebar.css
2025-07-30 10:29:07,070 WARNING  Not Found: /static/admin/js/theme.js
2025-07-30 10:29:07,071 WARNING  Not Found: /static/admin/css/dashboard.css
2025-07-30 10:29:07,072 WARNING  Not Found: /static/admin/css/responsive.css
2025-07-30 10:29:07,215 WARNING  Not Found: /static/admin/css/dashboard.css
2025-07-30 10:29:07,216 WARNING  Not Found: /static/admin/css/responsive.css
2025-07-30 10:29:07,217 WARNING  Not Found: /static/admin/js/nav_sidebar.js
2025-07-30 10:29:07,219 WARNING  Not Found: /static/admin/css/nav_sidebar.css
2025-07-30 10:30:41,590 ERROR    Invalid HTTP_HOST header: '9b32206e9986.ngrok-free.app'. You may need to add '9b32206e9986.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '9b32206e9986.ngrok-free.app'. You may need to add '9b32206e9986.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:30:41,768 ERROR    Invalid HTTP_HOST header: '9b32206e9986.ngrok-free.app'. You may need to add '9b32206e9986.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '9b32206e9986.ngrok-free.app'. You may need to add '9b32206e9986.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:30:44,433 ERROR    Invalid HTTP_HOST header: '9b32206e9986.ngrok-free.app'. You may need to add '9b32206e9986.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '9b32206e9986.ngrok-free.app'. You may need to add '9b32206e9986.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:30:44,584 ERROR    Invalid HTTP_HOST header: '9b32206e9986.ngrok-free.app'. You may need to add '9b32206e9986.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '9b32206e9986.ngrok-free.app'. You may need to add '9b32206e9986.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:30:53,636 WARNING  Not Found: /static/admin/css/base.css
2025-07-30 10:30:53,638 WARNING  Not Found: /static/admin/css/dark_mode.css
2025-07-30 10:30:53,679 WARNING  Not Found: /static/admin/css/responsive.css
2025-07-30 10:30:53,681 WARNING  Not Found: /static/admin/css/dashboard.css
2025-07-30 10:30:53,681 WARNING  Not Found: /static/admin/js/theme.js
2025-07-30 10:30:53,683 WARNING  Not Found: /static/admin/css/nav_sidebar.css
2025-07-30 10:30:53,890 WARNING  Not Found: /static/admin/css/nav_sidebar.css
2025-07-30 10:30:53,890 WARNING  Not Found: /static/admin/js/nav_sidebar.js
2025-07-30 10:30:53,890 WARNING  Not Found: /static/admin/css/dashboard.css
2025-07-30 10:30:53,892 WARNING  Not Found: /static/admin/css/responsive.css
2025-07-30 10:32:47,724 ERROR    Invalid HTTP_HOST header: 'f47be74d2309.ngrok-free.app'. You may need to add 'f47be74d2309.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'f47be74d2309.ngrok-free.app'. You may need to add 'f47be74d2309.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:32:47,894 ERROR    Invalid HTTP_HOST header: 'f47be74d2309.ngrok-free.app'. You may need to add 'f47be74d2309.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'f47be74d2309.ngrok-free.app'. You may need to add 'f47be74d2309.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:33:22,808 ERROR    Invalid HTTP_HOST header: 'f47be74d2309.ngrok-free.app'. You may need to add 'f47be74d2309.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'f47be74d2309.ngrok-free.app'. You may need to add 'f47be74d2309.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:33:22,966 ERROR    Invalid HTTP_HOST header: 'f47be74d2309.ngrok-free.app'. You may need to add 'f47be74d2309.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'f47be74d2309.ngrok-free.app'. You may need to add 'f47be74d2309.ngrok-free.app' to ALLOWED_HOSTS.
2025-07-30 10:34:26,521 WARNING  Not Found: /
2025-07-30 10:34:50,799 WARNING  Not Found: /static/admin/css/base.css
2025-07-30 10:34:50,802 WARNING  Not Found: /static/admin/css/dark_mode.css
2025-07-30 10:34:50,845 WARNING  Not Found: /static/admin/css/dashboard.css
2025-07-30 10:34:50,846 WARNING  Not Found: /static/admin/css/responsive.css
2025-07-30 10:34:50,848 WARNING  Not Found: /static/admin/css/nav_sidebar.css
2025-07-30 10:34:50,849 WARNING  Not Found: /static/admin/js/theme.js
2025-07-30 10:34:50,957 WARNING  Not Found: /static/admin/css/responsive.css
2025-07-30 10:34:50,957 WARNING  Not Found: /static/admin/css/dashboard.css
2025-07-30 10:34:50,959 WARNING  Not Found: /static/admin/css/nav_sidebar.css
2025-07-30 10:34:50,960 WARNING  Not Found: /static/admin/js/nav_sidebar.js
